<nav>
<ul>
    <li><a href="gestaltlovene.php">Gestaltlovene</a></li>
     <li><a href="farver.php">Farver</a></li>
    <li><a href="typografi.php">Typografi</a></li>
    <li><a href="illustrator.php">Illustrator</a></li>
    <li><a href="photoshop.php">Photoshop</a></li>
    <li><a href="design.thinking.php">Design thinking</a></li>
    <li><a href="fotografering.php">Fotografering</a></li>
</ul>
</nav>